@Api_HostAddress = https://localhost:7296

GET https://localhost:7296/customers/cus123/contact/33fdab1b-6307-4cb6-b65b-3be8ca679b1d
Accept: application/json

###


POST {{Api_HostAddress}}/customers/Cus123/contact
Content-Type: application/json
{
  "firstName": "Watford",
  "lastName": "Hays",
  "email": "a@b.com",
  "label": "Bla",
  "telephone": "tel",
  "altTelephone": "89384",
  "postalAddress": {
      "code": "89",
      "name": "M",
      "line1": "Line 111",
      "line2": "Line 222",
      "line3": "Line 333",
      "region": "region 1",
      "country": "country 1",
      "locality": "GB"
    },
  "telephoneCode": "893",
  "altTelephoneCode": "892",
  "descriptors": [ 
    {
      "key": "K1",
      "value": "V1"
    }
  ]
}
###

PATCH {{Api_HostAddress}}/customers/Cus123/contact/33fdab1b-6307-4cb6-b65b-3be8ca679b1d
Content-Type: application/json
{
  "firstName": "Updated 1",
  "lastName": "Updated 2",
  "targetVersion": 1
}
###
