@Api_HostAddress = https://localhost:7296/api/v1

GET  {{Api_HostAddress}}/customers/cus123/contacts/50ae2e45-2b22-4c9b-9a2c-1683de73e0e2
Accept: application/json

###


POST {{Api_HostAddress}}/customers/Cus123/contacts
Content-Type: application/json
{
  "firstName": "Watford",
  "lastName": "Hays",
  "email": "a@b.com",
  "label": "Bla",
  "telephone": "tel",
  "altTelephone": "89384",
  "postalAddress": {
      "code": "89",
      "name": "M",
      "line1": "Line 111",
      "line2": "Line 222",
      "line3": "Line 333",
      "region": "region 1",
      "country": "country 1",
      "locality": "GB"
    },
  "telephoneCode": "893",
  "altTelephoneCode": "892",
  "descriptors": [ 
    {
      "key": "K1",
      "value": "V1"
    }
  ]
}
###

PATCH {{Api_HostAddress}}/customers/Cus123/contacts/50ae2e45-2b22-4c9b-9a2c-1683de73e0e2
Content-Type: application/json
{
  "firstName": "Updated 4",
  "lastName": "Updated 8",
  "targetVersion": 2
}
###

DELETE {{Api_HostAddress}}/customers/Cus123/contacts/33fdab1b-6307-4cb6-b65b-3be8ca679b1d
###

POST {{Api_HostAddress}}/customers/Cus123/contacts/50ae2e45-2b22-4c9b-9a2c-1683de73e0e2/submit
Content-Type: application/json
{
  "targetVersion": 4
}
###

POST {{Api_HostAddress}}/customers/Cus123/contacts/50ae2e45-2b22-4c9b-9a2c-1683de73e0e2/touch
###
