@Api_HostAddress = https://localhost:7296/api/v1

GET  {{Api_HostAddress}}/customers/Cus123/legal-entities/LE123456/bank-accounts/66d8be80-9df8-4fa6-b2df-004fa8ba8a24
Accept: application/json

###

POST {{Api_HostAddress}}/customers/Cus123/legal-entities/LE123456/bank-accounts
Content-Type: application/json
{
  "legalEntityId": "9938982",
  "bankAccountHolderNames": "Bank Account holder name 1",
  "accountNumber": "9938982",
  "bankCity": "Watford",
  "bankCountry": "GB",
  "bankName": "Lloyds",
  "billingDefault": true,
  "iban": "Iban 2",
  "name": "Bank account name",
  "sortCode": "Sort code 3",
  "swift": "Swift 4",
  "label": "Company main bank account",
  "descriptors": [
    {
      "key": "SomeBankKey",
      "value": "SomeBankValue"
    }
  ]
}
###

PATCH {{Api_HostAddress}}/customers/Cus123/legal-entities/LE123456/bank-accounts/66d8be80-9df8-4fa6-b2df-004fa8ba8a24
Content-Type: application/json
{
  "name": "Description Updated 4",
  "iban": "LK",
  "targetVersion": 4
}
###

DELETE {{Api_HostAddress}}/customers/Cus123/legal-entities/LE123456/bank-accounts/66d8be80-9df8-4fa6-b2df-004fa8ba8a24
###

POST {{Api_HostAddress}}/customers/Cus123/legal-entities/LE123456/bank-accounts/66d8be80-9df8-4fa6-b2df-004fa8ba8a24/submit
Content-Type: application/json
{
  "targetVersion": 1
}
###

POST {{Api_HostAddress}}/customers/Cus123/legal-entities/LE123456/bank-accounts/66d8be80-9df8-4fa6-b2df-004fa8ba8a24/touch
###
