@Api_HostAddress = https://localhost:7296/api/v1

GET  {{Api_HostAddress}}/customers/Cus123/billing-groups/f657d315-b2b7-4f03-966b-194524afcd50
Accept: application/json

###

POST {{Api_HostAddress}}/customers/Cus123/billing-groups
Content-Type: application/json
{
  "billingBankAccountId": "A1234",
  "description": "Bank Description",
  "legalEntityId": "9938982",
  "name": "Company billing",
  "label": "Secondary billing account",
  "descriptors": [
    {
      "key": "SomeKey",
      "value": "SomeValue"
    }
  ]
}
###

PATCH {{Api_HostAddress}}/customers/Cus123/billing-groups/ae4113d0-33d0-4fcb-86e2-1ed43749d3a4
Content-Type: application/json
{
  "description": "Description Updated 4",
  "name": "Name Updated 8",
  "targetVersion": 1
}
###

DELETE {{Api_HostAddress}}/customers/Cus123/billing-groups/ae4113d0-33d0-4fcb-86e2-1ed43749d3a4
###

POST {{Api_HostAddress}}/customers/Cus123/billing-groups/ae4113d0-33d0-4fcb-86e2-1ed43749d3a4/submit
Content-Type: application/json
{
  "targetVersion": 2
}
###

POST {{Api_HostAddress}}/customers/Cus123/billing-groups/ae4113d0-33d0-4fcb-86e2-1ed43749d3a4/touch
###
