@Api_HostAddress = https://localhost:7296/api/v1

GET  {{Api_HostAddress}}/customers/cus123/contacts/a9e8b9e8-1fff-4591-ad8b-f27537d50956
Accept: application/json

###

POST {{Api_HostAddress}}/customers/Cus123/contacts
Content-Type: application/json
{
  "firstName": "Watford",
  "lastName": "Hays",
  "email": "a@b.com",
  "label": "Bla",
  "telephone": "tel",
  "altTelephone": "89384",
  "postalAddress": {
      "code": "89",
      "name": "M",
      "line1": "Line 111",
      "line2": "Line 222",
      "line3": "Line 333",
      "region": "region 1",
      "country": "country 1",
      "locality": "GB"
    },
  "telephoneCode": "893",
  "altTelephoneCode": "892",
  "descriptors": [ 
    {
      "key": "K1",
      "value": "V1"
    }
  ]
}
###

PATCH {{Api_HostAddress}}/customers/Cus123/contacts/a9e8b9e8-1fff-4591-ad8b-f27537d50956
Content-Type: application/json
{
  "firstName": "Updated 4",
  "lastName": "Updated 8",
  "targetVersion": 1
}
###

DELETE {{Api_HostAddress}}/customers/Cus123/contacts/a9e8b9e8-1fff-4591-ad8b-f27537d50956
###

POST {{Api_HostAddress}}/customers/Cus123/contacts/a9e8b9e8-1fff-4591-ad8b-f27537d50956/submit
Content-Type: application/json
{
  "targetVersion": 2
}
###

POST {{Api_HostAddress}}/customers/Cus123/contacts/a9e8b9e8-1fff-4591-ad8b-f27537d50956/touch
###
