@Api_HostAddress = https://localhost:7296/api/v1

GET  {{Api_HostAddress}}/customers/Cus123/contacts/b8891815-4dac-49fa-9e2d-770694278ce8
Accept: application/json

###

POST {{Api_HostAddress}}/customers/Cus123/contacts
Content-Type: application/json
{
  "name": "Technical contact",
  "email": "a@b.com",
  "labels": ["Bla1", "Bla2"],
  "telephone": "tel",
  "telephone_code": "87893",
  "postal_address": {
      "code": "89",
      "name": "M",
      "line1": "Line 111",
      "line2": "Line 222",
      "line3": "Line 333",
      "region": "region 1",
      "country": "country 1",
      "locality": "GB"
    },
  "alt_telephone_code": "893",
  "alt_telephone": "892",
  "meta_data": {
    "interesting": "Info"
  },
  "system_data": {
    "this_does_not": "look right"
  }
}
###

PATCH {{Api_HostAddress}}/customers/Cus123/contacts/a9e8b9e8-1fff-4591-ad8b-f27537d50956
Content-Type: application/json
{
  "firstName": "Updated 4",
  "lastName": "Updated 8",
  "targetVersion": 1
}
###

DELETE {{Api_HostAddress}}/customers/Cus123/contacts/a9e8b9e8-1fff-4591-ad8b-f27537d50956
###

POST {{Api_HostAddress}}/customers/Cus123/contacts/dcc06ef9-b8b3-4889-ac08-cfc028e9314b/submit
Content-Type: application/json
{
  "targetVersion": 1
}
###

POST {{Api_HostAddress}}/customers/Cus123/contacts/b8891815-4dac-49fa-9e2d-770694278ce8/touch
###
