@Api_HostAddress = https://localhost:7296/api/v1

GET  {{Api_HostAddress}}/customers/Cus123/changes?legalEntityId=LE123456
Accept: application/json

###

POST  {{Api_HostAddress}}/customers/Cus123/submit-changes?legalEntityId=LE123456
Accept: application/json

###