@Api_HostAddress = https://localhost:7296/api/v1

POST  {{Api_HostAddress}}/customers
Content-Type: application/json
nwp-correlation-id: ce84956f-85e7-4587-9976-865c780d6f6d
nwp-client-id: AuthorisationServer
{
  "name": "my profile",
  "customer_id": "ABC229",
  "labels": ["interesting"],
  "meta_data": {
    "this_is": "interesting one"
  },
  "system_data": {
    "this_is": "system data"
  }
}


###
GET  {{Api_HostAddress}}/customers/ABC226
Accept: application/json
nwp-correlation-id: ce84956f-85e7-4587-9976-865c780d6f6d
nwp-client-id: Portal

###

PATCH  {{Api_HostAddress}}/customers/ABC229
Content-Type: application/json
nwp-correlation-id: ce84956f-85e7-4587-9976-865c780d6f6d
nwp-client-id: Portal
{
  "name": "not by profile",
  "meta_data": {
    "something": "good"
  }
}
###