@Api_HostAddress = https://localhost:7296/api/v1

GET  {{Api_HostAddress}}/customers/Cus123/legal-entities/67a2a0a9-7633-43a0-8c63-a74c50216a17
Accept: application/json

###

POST {{Api_HostAddress}}/customers/Cus123/legal-entities
Content-Type: application/json
{
  "name": "Amaxing",
  "tradingName": "Trading as Amaxing Ltd",
  "businessType": "Sole trader",
  "businessEmail": "e@m.com",
  "businessContacts": [
    {
      "contactId": "447c14ec-f184-44bf-84b2-61c1a61ee3da",
      "contactType": "Account"
    }
  ],
  "cardTurnoverPerAnnum": 10000,
  "turnoverPerAnnum": 30000,
  "companyRegistration": "REG12345",
  "vatRegistration": "VAR12324",
  "vatRegistrationStatus": "Pending",
  "dateBusinessStarted": "2023-02-14",
  "legalEntitiesWithControl": [
    {
      "controlTypes": [
        "Shareholder"
      ],
      "legalEntityId": "E65237"
    }
  ],
  "maximumTransactionValue": 10000,
  "merchantCategoryCode": "MCC1",
  "standardIndustryClassification": "SIC2",
  "personsWithControl": [
    {
      "controlTypes": ["Shareholder"],
      "person": {
        "firstName": "Some",
        "dateOfBirth": "1981-07-27",
        "title": "Mr",
        "lastName": "Form",
        "middleName": "Not Middle",
        "nationality": "IL",
        "address": {
           "code": "AB1 2CD",
            "country": "GB",
            "line1": "Line 1",
            "line2": "Line 22",
            "line3": "Line 33",
            "locality": "locality 44",
            "name": "House name",
            "region": "Suffolk"
        }
      }
    }
  ],
  "registeredAddresses": [
    {
      "address":  
      {
        "name": "House name",
        "code": "AB1 2CD",
        "country": "GB",
        "line1": "Line 1",
        "line2": "Line 22",
        "line3": "Line 33",
        "locality": "locality 44",
        "region": "Suffolk"
       },
       "current": true,
       "dateFrom": "2023-09-10"
    }
  ]
}
###

PATCH {{Api_HostAddress}}/customers/Cus123/legal-entities/67a2a0a9-7633-43a0-8c63-a74c50216a17
Content-Type: application/json
{
  "tradingName": "Updated 4",
  "businessEmail": "Updated 8",
  "targetVersion": 2
}
###

DELETE {{Api_HostAddress}}/customers/Cus123/legal-entities/67a2a0a9-7633-43a0-8c63-a74c50216a17
###

POST {{Api_HostAddress}}/customers/Cus123/legal-entities/67a2a0a9-7633-43a0-8c63-a74c50216a17/submit
Content-Type: application/json
{
  "targetVersion": 3
}
###

POST {{Api_HostAddress}}/customers/Cus123/legal-entities/67a2a0a9-7633-43a0-8c63-a74c50216a17/touch
###

GET {{Api_HostAddress}}/customers/legal-entities/find-by-contact?customerId=Cus123&ContactId=447c14ec-f184-44bf-84b2-61c1a61ee3da
###
