@Api_HostAddress = https://localhost:7296/api/v1

GET  {{Api_HostAddress}}/customers/Cus123/legal-entities/67a2a0a9-7633-43a0-8c63-a74c50216a17
Accept: application/json

###

POST {{Api_HostAddress}}/customers/Cus123/legal-entities
Content-Type: application/json
{
  "name": "Amaxing",
  "trading_name": "Trading as Amaxing Ltd",
  "operating_as": "Amaxing Ltd",
  "nature_of_business": "Retail",
  "business_type": "SoleTrader",
  "business_email": "e@m.com",
  "business_contacts": [
    {
      "contact_id": "447c14ec-f184-44bf-84b2-61c1a61ee3da",
      "contact_type": "Financial"
    }
  ],
  "goods_ownership": "ThirdParty",
  "card_turnover_per_annum": 10000,
  "turnover_per_annum": 30000,
  "company_registration": "REG12345",
  "charity_registration": "C1934",
  "national_insurance_number": "SC10920J",
  "business_identification": "BI12345",
  "vat_registration": "VAR12324",
  "vat_registration_status": "Pending",
  "date_business_created": "2023-02-14",
  "date_trading_started": "2023-03-01",
  "legal_entity_with_control": [
    {
      "control_types": [
        "Shareholder"
      ],
      "legal_entity_id": "E65237",
      "ownership_percentage": 25,
      "date_from": "2023-09-10",
      "date_to": "2024-09-10"
    }
  ],
  "maximum_transaction_value": 10000,
  "merchant_category_code": "MCC1",
  "standard_industry_classification": "SIC2",
  "trading_industry_classification": "TIC3",
  "persons_with_control": [
    {
      "control_types": ["Shareholder"],
      "person": {
        "first_name": "Some",
        "date_of_birth": "1981-07-27",
        "title": "Mr",
        "last_name": "Form",
        "middle_name": "Not Middle",
        "nationality": "IL",
        "address": {
           "code": "AB1 2CD",
            "country": "GB",
            "line1": "Line 1",
            "line2": "Line 22",
            "line3": "Line 33",
            "locality": "locality 44",
            "name": "House name",
            "region": "Suffolk"
        },
        "person_identification": "CIN12323"
      }
    }
  ],
  "registered_addresses": [
    {
      "address":  
      {
        "name": "House name",
        "code": "AB1 2CD",
        "country": "GB",
        "line1": "Line 1",
        "line2": "Line 22",
        "line3": "Line 33",
        "locality": "locality 44",
        "region": "Suffolk"
       },
       "current": true,
       "date_from": "2023-09-10"
    }
  ],
  "country_of_authority": "GB",
  "partners_with_interest": [
    {
      "attribution_type": ["Introducer", "Affiliate"],
      "legal_entity_id": "94343",
      "meta_data": {
        "key1": "value1",
        "key2": "value2"
      }
    }
  ],
  "meta_data": {
    "where_opened": "UK1",
    "opened_date": "2020-01-01"
  },
  "system_data": {
    "internal_note": "Send Legal entity",
    "created_date": "2024-01-01T10:00:00Z"
  },
  "labels": ["My company"]
}
###

PATCH {{Api_HostAddress}}/customers/Cus123/legal-entities/67a2a0a9-7633-43a0-8c63-a74c50216a17
Content-Type: application/json
{
  "tradingName": "Updated 4",
  "businessEmail": "Updated 8",
  "targetVersion": 2
}
###

DELETE {{Api_HostAddress}}/customers/Cus123/legal-entities/67a2a0a9-7633-43a0-8c63-a74c50216a17
###

POST {{Api_HostAddress}}/customers/Cus123/legal-entities/67a2a0a9-7633-43a0-8c63-a74c50216a17/submit
Content-Type: application/json
{
  "targetVersion": 3
}
###

POST {{Api_HostAddress}}/customers/Cus123/legal-entities/67a2a0a9-7633-43a0-8c63-a74c50216a17/touch
###

GET {{Api_HostAddress}}/customers/legal-entities/find-by-contact?customerId=Cus123&ContactId=447c14ec-f184-44bf-84b2-61c1a61ee3da
###
