@Api_HostAddress = https://localhost:7296/api/v1

GET  {{Api_HostAddress}}/customers/Cus123/legal-entities/LE123456/trading-locations/ddf4fde3-bc61-4ed7-8684-1546f6c3018c
Accept: application/json

###

POST {{Api_HostAddress}}/customers/Cus123/legal-entities/LE123456/trading-locations
Content-Type: application/json
{
  "address":  {
      "code": "89",
      "name": "M",
      "line1": "Line 111",
      "line2": "Line 222",
      "line3": "Line 333",
      "region": "region 1",
      "country": "country 1",
      "city": "watford",
      "locality": "GB"
    },
  "contacts": [
    {
      "contact_id": "123",
      "contact_type": "Support"
    }
  ],
  "name": "trading name",
  "website": "https://example.com",
  "meta_data": {
    "where_opened": "My home address",
    "moved_in_date": "2024-01-01"
  },
  "system_data": {
    "internal_note": "We should not allow home addresses"    
  },
  "labels": ["My home location"]
}
###

PATCH {{Api_HostAddress}}/customers/Cus123/legal-entities/LE123456/trading-locations/ddf4fde3-bc61-4ed7-8684-1546f6c3018c
Content-Type: application/json
{
  "name": "Description Updated 5",
  "target_draft_version": 1
}
###

DELETE {{Api_HostAddress}}/customers/Cus123/legal-entities/LE123456/trading-locations/a04c109a-ab3b-407d-beec-1f9c85d2bb08
###

POST {{Api_HostAddress}}/customers/Cus123/legal-entities/LE123456/trading-locations/ddf4fde3-bc61-4ed7-8684-1546f6c3018c/submit
Content-Type: application/json
{
  "reason": "Just like it",
  "target_draft_version": 2
}
###

POST {{Api_HostAddress}}/customers/Cus123/legal-entities/LE123456/trading-locations/ddf4fde3-bc61-4ed7-8684-1546f6c3018c/touch
###
